version: "3.7"
services:
  backend:
    image: springcommunity/spring-petclinic-rest
    ports:
     -  "9966:9966"
    container_name: backend

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  frontend:
    image: barnabyrh/spcfrontend:v1
    ports:
     -  "8080:8080"
     -  "4200:4200"
    links:
     -  backend
       
  nginx:
    image: nginx:latest
    ports:
     -  "80:80"    
