- name: Updates 
  hosts: all
  become: true
  tasks:
  - name: Updating 
    command: sudo apt-get update -y

  - name: Java
    become: true
    shell: sudo apt install openjdk-8-jdk -y

- hosts: jenkins
  become: true
  roles:
    - ansible-role-jenkins
  tasks:
  - name: Jenkins User
    command: sudo usermod -aG sudo jenkins
  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
  - name: Print init password Jenkins
    debug:
      var: result.stdout
  
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: "reload docker"
    service:
      name: docker
      state: reloaded
- hosts: all
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      groups: 
      - docker
      append: true 
      shell: /bin/bash
