- hosts: localhost
  connection: local
  tasks:
  - name: "generate key pair"
    openssh_keypair:
      path: ~/.ssh/id_rsa


- hosts: all
  become: true
  tasks:
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: "reload docker"
    service:
      name: docker
      state: reloaded

- hosts: all
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      groups: 
      - docker
      append: true
      shell: /bin/bash
  


- name: Install Jenkins
  hosts: jenkins
  become: true 
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: jenkins gpg key
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present
  - name: jenkins apt repo
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present
  - name: jenkins install
    apt:
      name: jenkins
      state: latest
      update_cache: true
  - name: jenkins service
    service:
      name: jenkins
      state: started
  - name: "python pip"
    apt:
      name: python-pip
      state: latest
      update_cache: true
  - name: "docker sdk"
    pip:
     name: docker
  - name: "docker registry container"
    docker_container:
      name: registry
      image: registry
      ports:
      - "5000:5000"
  
  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
  - name: Print init password Jenkins
    debug:
      var: result.stdout
